fix: upgrade preact/swr/typescript
Also run prettier because I missed that in the last commit.

The upgrade to swr caused an error with tsc:
```
node_modules/swr/dist/use-swr.d.ts:1:23 - error TS2688: Cannot find type definition file for 'react'.

/// <reference types="react" />
```

The Preact docs suggest enabling `skipLibCheck` in tsconfig, and this
caused the error to go away.